default_install_hook_types: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-shebang-scripts-are-executable
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-symlinks
        stages: [pre-commit]
      - id: destroyed-symlinks
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: fix-byte-order-marker
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        args: [--whitespaces-count, "2"] # defaults to: 4
        stages: [pre-commit]
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: forbid-binary
        stages: [pre-commit]
  - repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: 0.1.2
    hooks:
      - id: tidy-gitignore
        stages: [pre-commit]
  - repo: https://github.com/google/yamlfmt
    rev: v0.12.1
    hooks:
      - id: yamlfmt
        stages: [pre-commit]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.5
    hooks:
      - id: check-github-workflows
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        stages: [pre-commit]
