# The repository should depend on GitHub Actions as little as possible.
# Minimizing the dependency on GitHub actions will make it easier to migrate to
# other CI/CD tools if required and much of what it does can better served by a
# build system.
name: ci
on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
defaults:
  run:
    shell: bash
jobs:
  pre-commit:
    if: |
      github.event_name == 'merge_group' ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: PR Pre-commit CI
        uses: pre-commit/action@v3.0.1
      - name: PR Vale CI
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          reporter: github-check
      - name: Merge CI
        if: github.event_name == 'merge_group'
        run: |
          python -m pip install commitizen
          git log -1 --format=%B HEAD >| commit_msg.txt
          cz check --commit-msg-file commit_msg.txt
  vale:
    if: |
      github.event_name == 'merge_group' ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PR Vale CI
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          reporter: github-check
  hugo-build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  hugo-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: false
    env:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: hugo-build
    steps:
      - name: Deploy to GitHub Pages
        if: |
          github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4
