name: commitlint

on:
  merge_group:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install commitlint
        run: |
          npm install @commitlint/cli @commitlint/config-conventional --save-dev
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
      - name: Validate PR commit message
        run: echo ${{ github.event.pull_request.title}}\n\n${{ github.event.pull_request.body}} | npx commitlint
