name: commit-msg

on:
  merge_group:
    branches: [main]

jobs:
  commit-msg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
    - run: python -m pip install pre-commit
      shell: bash
    - run: pre-commit install --install-hooks -t commit-msg
      shell: bash
    - run: pre-commit run --hook-stage manual commitizen-branch
      shell: bash
