name: Validate code in the merge queue

on:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        pwd
        tree -a -I '.git'
        git status
        echo $GITHUB_CONTEXT
    - name: Run slow CI (emulated by a long sleep)
      run: sleep 60
